---

- name: install docker-image dependencies
  pacman: name=docker,git,make,devtools,fakeroot,fakechroot state=present

- name: create docker-image user
  user: name={{ docker_image_user }} shell=/bin/bash home="{{ docker_image_home }}" createhome=yes

- name: clone archlinux-docker repository
  become: yes
  become_user: "{{docker_image_user}}"
  git: repo="{{docker_image_git_remote}}" version="{{ docker_image_git_tag }}" dest="{{ docker_image_git_dir }}" force=yes

- name: install docker_image service
  template: src='docker-image.service.j2' dest='/etc/systemd/system/docker-image.service' owner=root group=root mode=0644
  notify:
    - daemon reload

- name: install docker_image timer
  template: src='docker-image.timer.j2' dest='/etc/systemd/system/docker-image.timer' owner=root group=root mode=0644
  notify:
    - daemon reload

- name: start and enable docker_image_build timer
  service: name='docker-image.timer' enabled=yes state=started
