---

docker_image_user: 'docker-image'
docker_image_home: '/srv/docker-image'
docker_image_git_dir: '/srv/docker-image/archlinux-docker'
docker_image_git_remote: 'https://github.com/archlinux/archlinux-docker.git'
docker_image_git_tag: 'v1.0'
docker_image_time: '*-*-05 00:00:00'
